version: "3.8"

services:
  mongodb:
    image: mongo:7.0
    container_name: cinema_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password1234
      MONGO_INITDB_DATABASE: cinema_db
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7.2-alpine
    container_name: cinema_redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass password1234

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: cinema_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password1234

volumes:
  mongodb_data: